"""
Semantic job-listing search backed by pgvector similarity search
(job_listings.embedding, vector(768), populated by jobs.py._embed_job on
create/crawl — same embedding service/dimension as candidate_profiles.embedding,
which is what makes app.api.candidates.get_suggested_jobs's cosine matching
work). Mirrors business_vector_retriever.py's shape so pipeline.py/
knowledge_fusion.py can treat jobs as a third evidence source alongside
businesses and news.

Added because the chat pipeline had ZERO integration with job_listings —
only businesses_demo — so a job-search question like "giới thiệu công việc
backend" could never be answered with real job data, only company data.
"""
import logging
from typing import Dict, List, Optional

import psycopg2
from psycopg2.extras import RealDictCursor

from app.config import settings

logger = logging.getLogger(__name__)


class JobVectorRetriever:
    def __init__(self, embedding_service=None):
        # Reuses the shared 768-dim service (app.dependencies) — NOT
        # business_vector_retriever's own 1536-dim instance, since
        # job_listings.embedding was generated by the shared service
        # (jobs.py._embed_job), a different embedding model/dimension than
        # businesses_demo.embedding. Imported lazily — app.dependencies
        # imports app.ai.pipeline at module load time, which imports this
        # module, so a top-level import here would be circular.
        if embedding_service is None:
            from app.dependencies import get_embedding_service
            embedding_service = get_embedding_service()
        self.embedding_service = embedding_service

    def search(
        self,
        query: str,
        top_k: int = 10,
        threshold: float = 0.35,
        filters: Optional[Dict] = None,
    ) -> List[Dict]:
        try:
            query_embedding = self.embedding_service.generate_query_embedding(query)
            embedding_str = '[' + ','.join(map(str, query_embedding)) + ']'

            conn = psycopg2.connect(**settings.database_url)
            try:
                cur = conn.cursor(cursor_factory=RealDictCursor)

                sql = """
                    SELECT
                        j.id,
                        j.tieu_de as title,
                        j.ten_doanh_nghiep as company_name,
                        j.dia_diem as location,
                        j.ky_nang as skills,
                        j.phuc_loi as benefits,
                        j.mo_ta_cong_viec as description,
                        j.url,
                        j.hinh_thuc_lam_viec as employment_type,
                        j.kinh_nghiem_thang as months_of_experience,
                        COALESCE(b.nganh_nghe, j.ai_industry) as industry,
                        1 - (j.embedding <=> %s::vector) as similarity
                    FROM job_listings j
                    LEFT JOIN businesses_demo b ON b.id = j.business_id
                    WHERE j.embedding IS NOT NULL AND j.trang_thai = 'Da_duyet' AND (j.han_nop IS NULL OR j.han_nop >= CURRENT_DATE)
                """
                params = [embedding_str]

                if filters:
                    if filters.get('location'):
                        sql += " AND j.dia_diem ILIKE %s"
                        params.append(f"%{filters['location']}%")
                    if filters.get('industry'):
                        sql += " AND COALESCE(b.nganh_nghe, j.ai_industry) ILIKE %s"
                        params.append(f"%{filters['industry']}%")

                sql += " ORDER BY j.embedding <=> %s::vector LIMIT %s"
                params.extend([embedding_str, top_k])

                cur.execute(sql, params)
                rows = cur.fetchall()
            finally:
                conn.close()

            results = [dict(row) for row in rows if row['similarity'] >= threshold]
            logger.info(f"JobVectorRetriever: {len(results)}/{len(rows)} above threshold {threshold}")
            return results

        except Exception as e:
            logger.error(f"JobVectorRetriever search failed: {e}", exc_info=True)
            return []

    def list_recent(self, limit: int = 10, filters: Optional[Dict] = None) -> List[Dict]:
        """Fallback for queries with no topical content to embed against
        (e.g. "có việc làm mới không") — mirrors news_vector_retriever's
        list_recent / business's SQL-filter fallback."""
        try:
            conn = psycopg2.connect(**settings.database_url)
            try:
                cur = conn.cursor(cursor_factory=RealDictCursor)
                sql = """
                    SELECT
                        j.id, j.tieu_de as title, j.ten_doanh_nghiep as company_name,
                        j.dia_diem as location, j.ky_nang as skills, j.phuc_loi as benefits,
                        j.mo_ta_cong_viec as description, j.url,
                        j.hinh_thuc_lam_viec as employment_type, j.kinh_nghiem_thang as months_of_experience,
                        COALESCE(b.nganh_nghe, j.ai_industry) as industry
                    FROM job_listings j
                    LEFT JOIN businesses_demo b ON b.id = j.business_id
                    WHERE j.trang_thai = 'Da_duyet' AND (j.han_nop IS NULL OR j.han_nop >= CURRENT_DATE)
                """
                params = []
                if filters:
                    if filters.get('location'):
                        sql += " AND j.dia_diem ILIKE %s"
                        params.append(f"%{filters['location']}%")
                    if filters.get('industry'):
                        sql += " AND COALESCE(b.nganh_nghe, j.ai_industry) ILIKE %s"
                        params.append(f"%{filters['industry']}%")
                sql += " ORDER BY j.created_at DESC LIMIT %s"
                params.append(limit)

                cur.execute(sql, params)
                rows = cur.fetchall()
                return [dict(row) for row in rows]
            finally:
                conn.close()
        except Exception as e:
            logger.error(f"JobVectorRetriever.list_recent failed: {e}", exc_info=True)
            return []


_job_vector_retriever: Optional[JobVectorRetriever] = None


def get_job_vector_retriever() -> JobVectorRetriever:
    global _job_vector_retriever
    if _job_vector_retriever is None:
        _job_vector_retriever = JobVectorRetriever()
    return _job_vector_retriever
