"""
Re-generate embeddings for ALL station_news rows using the current
embedding model (gemini-embedding-2, 3072 dims to match the
embedding_vector column type). The 526 previously-populated rows were
generated by a different/incompatible model — cosine similarity between a
fresh query embedding and those stored vectors came back near-zero for
every row, i.e. they were unusable, not just missing. This overwrites
ALL rows, not just the ones with NULL embedding_vector.
"""
import sys
import time
import psycopg2
from psycopg2.extras import RealDictCursor

from app.config import settings
from app.services.embedding_service import EmbeddingService

NEWS_EMBEDDING_DIMENSION = 3072  # must match station_news.embedding_vector column type


def backfill(batch_pause_every: int = 50, batch_pause_seconds: int = 20, only_ids=None):
    conn = psycopg2.connect(**settings.database_url)
    cur = conn.cursor(cursor_factory=RealDictCursor)

    if only_ids:
        cur.execute("""
            SELECT id, tieu_de, tom_tat FROM station_news
            WHERE id = ANY(%s) ORDER BY id
        """, (list(only_ids),))
    else:
        cur.execute("""
            SELECT id, tieu_de, tom_tat
            FROM station_news
            ORDER BY id
        """)
    rows = cur.fetchall()
    total = len(rows)
    print(f"Found {total} news articles to (re-)embed")

    embedding_service = EmbeddingService(
        model=settings.EMBEDDING_MODEL,
        dimension=NEWS_EMBEDDING_DIMENSION,
    )

    success, failed = 0, 0
    for idx, row in enumerate(rows, 1):
        try:
            text = f"{row['tieu_de'] or ''}\n{row['tom_tat'] or ''}".strip()
            if len(text) < 10:
                print(f"  [{idx}/{total}] SKIP (too short): id={row['id']}")
                continue

            embedding = embedding_service.generate_document_embedding(text)
            cur.execute(
                "UPDATE station_news SET embedding_vector = %s::vector WHERE id = %s",
                ('[' + ','.join(map(str, embedding)) + ']', row['id']),
            )
            conn.commit()
            success += 1

            if idx % 25 == 0 or idx == total:
                print(f"  [{idx}/{total}] OK ({success} success, {failed} failed)")

            if idx % batch_pause_every == 0 and idx < total:
                print(f"  Pausing {batch_pause_seconds}s (rate limit)...")
                time.sleep(batch_pause_seconds)
            else:
                time.sleep(0.2)
        except Exception as e:
            failed += 1
            print(f"  [{idx}/{total}] FAILED (id={row.get('id')}): {e}")

    cur.close()
    conn.close()
    return {'success': success, 'failed': failed, 'total': total}


if __name__ == "__main__":
    auto_confirm = '--yes' in sys.argv
    ids_arg = next((a for a in sys.argv if a.startswith('--ids=')), None)
    only_ids = [int(x) for x in ids_arg[len('--ids='):].split(',')] if ids_arg else None

    if not auto_confirm:
        target = f"{len(only_ids)} specific rows" if only_ids else "ALL station_news rows"
        answer = input(f"Re-generate embeddings for {target}? (y/n): ")
        if answer.lower() != 'y':
            print("Cancelled")
            sys.exit(0)

    stats = backfill(only_ids=only_ids)
    print(f"\nDone: {stats['success']} success, {stats['failed']} failed, {stats['total']} total")
